language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
install:
  - pip install argcomplete
script:
  # There are no real unit or integration tests yet, so just execute the application
  - python http-ping -i 3 -t 10 https://example.com

  # Also test with different locales (the right number format returned by curl is important)
  - LANG=C python http-ping -i 3 -t 10 https://example.com
  - LANG=en_US.UTF-8 python http-ping -i 3 -t 10 https://example.com
  - LANG=de_DE.UTF-8 python http-ping -i 3 -t 10 https://example.com